spring:
#  security:
#    user:
#      name: admin
#      password: 123

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

springdoc:
  swagger-ui:
    path: /api.html