spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

springdoc:
  swagger-ui:
    path: /api.html

security:
  jwt:
    secret-key: fYOFTbk!klJt30*oYlRMXq5$Wa*#dPch
