spring:
#  security:
#    user:
#      name: admin
#      password: 123

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
#    url: jdbc:mysql://localhost:3306/DBCA
#    username: root
#    password:

springdoc:
  swagger-ui:
    path: /api.html